### ISSUE TITLE
How to get data?

### ISSUE THREAD

**Issue by doubleTroub1e** [AlexKrutoy/TapSwapBot#13]
Hey, how do yo get initial heders which are done from phone? do you use some emulator?

**Comment by ButCheR-PRO** [comment]
![image](https://github.com/AlexKrutoy/TapSwapBot/assets/23020594/f1e03309-3236-46b3-a495-c88e9f7d3b0b)

**Comment by amirhossein-fzl** [comment]
> Hey, how do yo get initial heders which are done from phone? do you use some emulator?

Just install extension https://addons.mozilla.org/en-US/firefox/addon/resourceoverride and Add this rule in extension setting:

URL: *
from: */telegram-web-app.js
to: https://evgeniyvorobev.github.io/hamster-kombat-bot/telegram-web-app.js

You must use Telegram Web and Inspect Browser. This extension is also available for Chrome...

If you solve the current tap swap problem, I will be happy to provide it to us 🙏❤️

**Comment by amirhossein-fzl** [comment]
> ![image](https://private-user-images.githubusercontent.com/23020594/343021460-f1e03309-3236-46b3-a495-c88e9f7d3b0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzM0NDgsIm5iZiI6MTcxOTU3MzE0OCwicGF0aCI6Ii8yMzAyMDU5NC8zNDMwMjE0NjAtZjFlMDMzMDktMzIzNi00NmIzLWE0OTUtYzg4ZTlmN2QzYjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDExMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Y2MxYWI4ZWE3ZGE3ZGQzMGZmNDE1MjJlMDkzYTYzZjEyMDVjMjUwZjI4ZjUzYzcyODcwYjExODNjNzU2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jvP7Bj5hcVG46Ahl3daDrn2mwBgazgOw0RjHeHoCItQ)

You probably did not set the correct configuration. I ran it for about 1 week in three accounts and there was no problem...
