### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'webdriver/geckodriver'

### ISSUE THREAD

**Issue by razak95** [AlexKrutoy/TapSwapBot#7]
![image](https://github.com/AlexKrutoy/TapSwapBot/assets/15963928/dcd6723d-f280-4b37-939e-e6f41fbdf8e7)

Linux localhost 4.19.191+ #1 SMP PREEMPT Fri Apr 12 18:58:22 CST 2024 aarch64 Android

im using termux

**Comment by headNbyte** [comment]
@razak95 Have you verified that you have installed the firefox by running the command below?
`sh install.sh`

**Comment by CruistCoder** [comment]
![Снимок экрана 2024-06-15 180319](https://github.com/AlexKrutoy/TapSwapBot/assets/112680133/bc11a694-0982-4520-85ee-7ae89c7ecd72)
Please help me!

**Comment by CruistCoder** [comment]
> @razak95 Have you verified that you have installed the firefox by running the command below? `sh install.sh`

![Снимок экрана 2024-06-15 180319](https://github.com/AlexKrutoy/TapSwapBot/assets/112680133/98b39063-c1d9-42ba-9598-6738d8b1bb34)
Please help me! I am install sh install.sh
P.S: this ubuntu server

**Comment by headNbyte** [comment]
@razak95 @CruistCoder please run this command and try again:
```
sudo tee -a /etc/hosts <<EOF
127.0.0.1 localhost
EOF
```
